---
baseurl: "https://insomnia.rest/"
languageCode: "en-us"
copyright: "Floating Keyboard Software, Victoria BC, Canada"
title: "Insomnia REST Client"
theme: "hugo-insomnia-theme"
publishdir: "_hugo"
disqusShortname: "insomnia-rest"
googleAnalytics: "UA-9837747-12"
permalinks:
  documentation: /documentation/:slug
menu:
  main:
    - Name: "Pricing"
      Identifier: "pricing"
      URL: "/pricing/"
      Weight: 2
    - Name: "Docs"
      Identifier: "docs"
      URL: "/documentation/"
      Weight: 1
    - Name: "Blog"
      Identifier: "blog"
      URL: "/blog/"
      Weight: 2
    - Name: "Download"
      Identifier: "download"
      URL: "/download/"
      Weight: 3
    - Name: "Account"
      Identifier: "account"
      Pre: "button"
      URL: "/app/account/"
      Weight: 10
    - Name: "Sign Up"
      Identifier: "signup"
      Pre: "button"
      URL: "/app/signup/"
      Weight: 10
    - Name: "Download"
      Identifier: "download"
      URL: "/download/"
      Weight: 100
  footer:
    - Name: Licence
      Identifier: eula
      URL: /eula/
      weight: 0
    - Name: Terms
      Identifier: terms
      URL: /terms/
      weight: 1
#    - Name: Blog
#      Identifier: blog
#      URL: /blog/
#      weight: 2
    - Name: Teams
      Identifier: teams
      URL: /teams/
      weight: 3
    - Name: Plus
      Identifier: plus
      URL: /plus/
      weight: 4
    - Name: Transparency
      Identifier: transparency
      URL: /transparency/
      weight: 5
    - Name: Changelog
      Identifier: changelog
      URL: /changelog/
      weight: 6
    - Name: Support
      Identifier: support
      URL: /documentation/support-and-feedback/
      weight: -1
  docs:
      - Name: ""
        Identifier: "welcome"
        Weight: 0
      - Name: "Getting Started"
        Identifier: "starting"
        Weight: 1
      - Name: "Help Topics"
        Identifier: "topics"
        Weight: 2
      - Name: "Other"
        Identifier: "other"
        Weight: 3
author:
  name: "Gregory Schier"
  image: "me.jpg"
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
params:
  copyrightURL: "https://floatingkeyboard.com"
  repo: "https://github.com/getinsomnia/website"
  docsCategories:
    - "welcome"
    - "starting"
    - "topics"
  stylesheets:
    - "main.css"
  scripts:
    - "main.js"
    - "build/app.min.js"
    - "lib/forge.min.js"
  email: "support@insomnia.rest"
  pageNotFoundTitle: "Sorry, that page doesn't exist"
  shortName: "Insomnia"
  bio: "Independent software developer"
  location: "Victoria BC, Canada"
  description: "A powerful REST API Client with cookie management, environment variables, code generation, and authentication for Mac, Window, and Linux"
  twitter: "GetInsomnia"
  googlePlus: "InsomniaRest"
  keepReadingStr: "Read More"
pygmentsCodeFences: true
pygmentsStyle: "monokai"
pygmentsUseClasses: true
metaDataFormat: "yaml"
blackfriday:
  fractions: false
